CREATE TABLE IF NOT EXISTS ChatRoom
(
  id INTEGER NOT NULL PRIMARY KEY,
  creator_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  category INTEGER NOT NULL,
  FOREIGN KEY(creator_id) REFERENCES User(id) ON DELETE CASCADE
);
